### ISSUE TITLE
Todo List (For dopamine purposes)

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/yt-subs-count#1]
- [ ] **Create to do list**

---

- [ ] **Manage youtube credential on a json file**

- [ ] **Get youtube information**
  - [ ] Channel name
  - [ ] Profile image
  - [ ] Total subscribers

- [ ] **Design**
  - [ ] Odometer
