### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by izaiasmachado** [izaiasmachado/yt-subs-count#2]
- [x] Todo list

--- 

- [x] User url input
- [ ] Create a YouTube search method

---
- [ ] **GET youtube information**
  - [ ] Channel name
  - [ ] Profile image
  - [ ] Subscribers number
  - [ ] Channel description
